"""add retailer column to scrape_runs

Revision ID: 6f7c90dc57c3
Revises: 0013
Create Date: 2026-07-01 16:47:50.990554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f7c90dc57c3'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('retailer', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'retailer')
    # ### end Alembic commands ###
